### ISSUE TITLE
https://www.lexico.com/en/definition/%s doesn't show a pupop window

### ISSUE THREAD

**Issue by kktt007** [Pitmairen/selection-search#101]
Thanks selection-search. I use it to learn English every day. I saves my lots of time after i use selection search.
It  seems doesn't work on https://www.lexico.com/en/definition/%s , there's no a popup window appear.
Appreciate selection search.

**Comment by Pitmairen** [comment]
It looks like the site is using some javascript that is blocking the mouse click events that are used to open the popup. I'm not sure how easy it is to fix this without adding special handling for this site in the code. 


A workaround could be to enable the "Open on double click" which can be found under advanced settings for the popup menu on the options page. Then the popup should open if you double click a word on the page. The double click event is not blocked so it should work. 

One issue though is that if you accidentally open the popup it will not close again, because the mouse events that normally causes the popup to close are also blocked. There is an options "Auto hide Delay" that can be used to set a timeout to auto close the popup after a certain number of seconds.

Another option is to enable the context menu option and use the right click menu for this site, or you could use the toolbar popup by clicking the icon in the toolbar (must be enabled in options).

**Comment by kktt007** [comment]
Many thanks. You solved my questions very well.
 
Advanced setting "Open on double click" does work. 

"Auto hide delay" is so  useful. I have never use it before. I setting 1second, When i moved the cursor, i will disapper. Cool. automatic.

Thanks, dear Pitmairen. Selection search is my top one extension, i can't live without it.

Another issue, i use Vivaldi on Archlinux KDE, DE and Resolution is a big issues on Linux. Maybe i didn't configure it well. My questions is Selection Search can't appear completely in one column. I i must reduce lots of websites. Maybe two columns could solve this issues. If should i open a new topic for this feature?

**Comment by Pitmairen** [comment]
Great that the workarounds was useful. :+1: 

Yes, please create another issue. Then it is easier to keep track of the issues and find them later.

Also if you can add a screenshot of the issue issue in Vivaldi it would make it easier to understand what you mean.
