### ISSUE TITLE
Double click activation ignores “show in inputs” preference

### ISSUE THREAD

**Issue by bsiegel** [Pitmairen/selection-search#64]
Regardless of your “show in inputs” setting and your “Auto show in inputs” setting, double clicking text will always pop up the selection search inside HTML inputs and textareas.

**Comment by Pitmairen** [comment]
Yes, that is a bug.

**Comment by Pitmairen** [comment]
Maybe it is better to just always disable the double click activator in input fields. I would assume that usually when someone double clicks a word in the input it is to remove it from the input. Then it is annoying to have the popup open. It can always be opened using the ctrl + click option if the  "show in inputs" option is enabled.

**Comment by tophf** [comment]
I rarely edit text and I often search for text so I loved the old behavior and I absolutely hate this change. Not a problem though as I'll be just using the old version loaded as an unpacked extension.

**Comment by Pitmairen** [comment]
I normally don't like to make changes to  things that has worked a certain way for a long time, because there is almost always someone relying on the way it used to work. But I assumed that this was such a small change that it would be ok, but I was wrong. :)  

I will try to make this change optional in the next release.

**Comment by Pitmairen** [comment]
I have re-enabled the previous behavior as the default, and added an option to disable the double click in inputs. It will be included in the next release.
